spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/supervision_livraisons}
spring.data.mongodb.database=supervision_livraisons
jwt.secret=c3VwZXJfc2VjcmV0X2tleV9mb3Jfc3VwZXJ2aXNpb25fYXBwXzIwMjQ=
jwt.expiration=86400000
server.port=8082
spring.jackson.serialization.write-dates-as-timestamps=false
