spring.data.mongodb.uri=mongodb+srv://awebbarouni_db_user:LxfUDzMgIKRz9RHX@cluster0.tvv0xie.mongodb.net/supervision_livraisons?retryWrites=true&w=majority
jwt.secret=c3VwZXJfc2VjcmV0X2tlZX9mb3Jfc3VwZXJ2aXNpb25fYXBwXzIwMjQ=
jwt.expiration=86400000
server.port=8082
spring.jackson.serialization.write-dates-as-timestamps=false
